### ISSUE TITLE
Gulp watch and "hot-deploy" files is broken since Liferay DXP Service-Pack 13

### ISSUE THREAD

**Issue by pieplu** [liferay/liferay-theme-tasks#52] opened 2017-05-11 16:57 UTC
Since Liferay Service-Pack 13, the gogo shell command `update <bundleID> webbundledir:file:...` stop working.

The `gulp watch` command is broken.

Is no more possible to have a decent front-end theme developement workflow. For every scss, js or ftl file change, we need to lanch manually a complete theme build.

Thanks in advance.

**Comment by Robert-Frampton** [comment] 2017-05-11 17:55
Hey @pieplu 

Thanks for reporting the issue. Since this appears to be an issue with Service-Pack 13 and not with the gulp task itself, it would be best to report this issue under the appropriate Liferay Support channels. 

However, I'll leave the issue open until the root cause of the problem is established. 

Thank you,

**Comment by pieplu** [comment] 2017-05-11 20:38
Thanks, a bug report can be found on this place: https://issues.liferay.com/browse/LPS-72409

**Comment by BenjaminBini** [comment] 2017-07-25 10:02
It is broken in GA4. Can anyone patch the CE edition please? It does not seem right to have a broken theme development workflow in CE Edition.

**Comment by gamerson** [comment] 2017-07-27 17:46
Hey Benjamin,

This isn't the easiest thing in the world, but it should work to 'patch'
GA4.

1) clone https://github.com/liferay/liferay-portal source

2) cd
modules/apps/static/portal-osgi-web/portal-osgi-web-wab-reference-support
3) gradle jar
4) cp
../../../../../tools/sdk/dist/com.liferay.portal.osgi.web.wab.reference.support-1.0.8.jar
${liferay_home}/osgi/static/override
5) start Liferay




--
Greg Amerson
Backend Developer Tools
Liferay, Inc. www.liferay.com

**Comment by BenjaminBini** [comment] 2017-09-01 08:20
Thank you that's what I did and it works well (even if for some reason I have to stop the original module manually with gogo shell). Would still be nice to include a hotfix in the release though, not great to have a broken official version.

**Comment by jbalsas** [comment] 2018-08-27 15:44
Closing here for now. I think we added some fix to the way our wabextender was working to fix this, so this should be fixed in `7.1`, and hopefully make it all the way back to `7.0`

**Closed by jbalsas** 2018-08-27 15:44 UTC
