### ISSUE TITLE
Unable to select asset type in Windows cmd

### ISSUE THREAD

**Issue by petersiman** [liferay/liferay-theme-tasks#2] opened 2015-10-13 10:39 UTC
Hi, I am trying to extend a theme using
`gulp extend`
but I am unable to select one of options in first step (the arrow keys don't do anything)
![image](https://cloud.githubusercontent.com/assets/2827734/10452710/f859791c-71a6-11e5-90c7-5bec5b98d0a2.png)
Only first option can be selected in my command line. I have tried this several times, but with no success. 
Interresting thing is, that after passing the first step, the selection with arrow keys works just fine in the second step
![image](https://cloud.githubusercontent.com/assets/2827734/10452737/2f0fe9dc-71a7-11e5-9dd3-6556d8ca4009.png)
![image](https://cloud.githubusercontent.com/assets/2827734/10452742/36ca6f08-71a7-11e5-8881-e96803f0b2f0.png)

Any help is appriciated.
Shimon

**Comment by natecavanaugh** [comment] 2015-10-15 19:53
Hi Shimon, could you let us know what version of Windows you're using?

**Comment by petersiman** [comment] 2015-10-16 08:41
Hi Nate, thank you for reply. 
I am using Windows 10. I could try to debug this behaviour, but I am not sure where exactly should I look to see this wizard behavior. I could spare you the work with trying to simulate this problem ;)

**Comment by Robert-Frampton** [comment] 2015-10-20 18:03
Hi Shimon,

I was able to reproduce the issue on a Win10 vm. Unfortunately it looks like a known Node.js issue (https://github.com/nodejs/node/issues/2996). I'll try to implement a temporary workaround for Windows 10 developers, as I'm unsure when the root issue will be addressed in Node.

**Comment by Robert-Frampton** [comment] 2016-05-11 22:01
Closing as the workaround has been implemented for some time now.

**Closed by Robert-Frampton** 2016-05-11 22:01 UTC
Labels: bug
